--------------------------------------------------------
--  Fichier créé - mercredi-avril-28-2021   
--------------------------------------------------------
DROP TABLE "FERIEL"."PLAT";
DROP TABLE "FERIEL"."RECETTE";
--------------------------------------------------------
--  DDL for Table PLAT
--------------------------------------------------------

  CREATE TABLE "FERIEL"."PLAT" 
   (	"ID_PL" NUMBER, 
	"NOM_PL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NB_CALORIES" NUMBER, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETTE
--------------------------------------------------------

  CREATE TABLE "FERIEL"."RECETTE" 
   (	"ID_RE" NUMBER, 
	"NOM_RE" VARCHAR2(20 BYTE), 
	"INGREDIENTS" VARCHAR2(20 BYTE), 
	"ORIGINE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FERIEL.PLAT
SET DEFINE OFF;
Insert into FERIEL.PLAT (ID_PL,NOM_PL,TYPE,NB_CALORIES,PRIX) values ('24','couscous','pates','600','8');
Insert into FERIEL.PLAT (ID_PL,NOM_PL,TYPE,NB_CALORIES,PRIX) values ('1','steak','viande','156','40');
Insert into FERIEL.PLAT (ID_PL,NOM_PL,TYPE,NB_CALORIES,PRIX) values ('6','soupe','entr??e','40','6');
Insert into FERIEL.PLAT (ID_PL,NOM_PL,TYPE,NB_CALORIES,PRIX) values ('13','chawarma','viande','400','8');
Insert into FERIEL.PLAT (ID_PL,NOM_PL,TYPE,NB_CALORIES,PRIX) values ('5','baguette_farcie','sandwich','800','8');
Insert into FERIEL.PLAT (ID_PL,NOM_PL,TYPE,NB_CALORIES,PRIX) values ('18','riz','pates','300','12');
REM INSERTING into FERIEL.RECETTE
SET DEFINE OFF;
Insert into FERIEL.RECETTE (ID_RE,NOM_RE,INGREDIENTS,ORIGINE) values ('12','croissant','patefeuilltee','italie');
Insert into FERIEL.RECETTE (ID_RE,NOM_RE,INGREDIENTS,ORIGINE) values ('2','pain','farine','france');
Insert into FERIEL.RECETTE (ID_RE,NOM_RE,INGREDIENTS,ORIGINE) values ('6','crepe','farine','france');
--------------------------------------------------------
--  DDL for Index PLAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERIEL"."PLAT_PK" ON "FERIEL"."PLAT" ("ID_PL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECETTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERIEL"."RECETTE_PK" ON "FERIEL"."RECETTE" ("ID_RE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PLAT
--------------------------------------------------------

  ALTER TABLE "FERIEL"."PLAT" ADD CONSTRAINT "PLAT_PK" PRIMARY KEY ("ID_PL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FERIEL"."PLAT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."PLAT" MODIFY ("NB_CALORIES" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."PLAT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."PLAT" MODIFY ("NOM_PL" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."PLAT" MODIFY ("ID_PL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETTE
--------------------------------------------------------

  ALTER TABLE "FERIEL"."RECETTE" ADD CONSTRAINT "RECETTE_PK" PRIMARY KEY ("ID_RE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FERIEL"."RECETTE" MODIFY ("ID_RE" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."RECETTE" MODIFY ("ORIGINE" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."RECETTE" MODIFY ("INGREDIENTS" NOT NULL ENABLE);
  ALTER TABLE "FERIEL"."RECETTE" MODIFY ("NOM_RE" NOT NULL ENABLE);
