--------------------------------------------------------
--  Fichier créé - vendredi-avril-30-2021   
--------------------------------------------------------
DROP TABLE "SKANDER"."COMMANDES";
DROP TABLE "SKANDER"."RESERVATIONS";
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "SKANDER"."COMMANDES" 
   (	"ID" NUMBER, 
	"PLAT" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "SKANDER"."RESERVATIONS" 
   (	"NUM" VARCHAR2(20 BYTE), 
	"HEURE" VARCHAR2(20 BYTE), 
	"NBRP" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SKANDER.COMMANDES
SET DEFINE OFF;
Insert into SKANDER.COMMANDES (ID,PLAT,ADRESSE,PRIX) values ('8','66','89','3');
Insert into SKANDER.COMMANDES (ID,PLAT,ADRESSE,PRIX) values ('7','7','4','12');
Insert into SKANDER.COMMANDES (ID,PLAT,ADRESSE,PRIX) values ('2','5','23','8');
REM INSERTING into SKANDER.RESERVATIONS
SET DEFINE OFF;
Insert into SKANDER.RESERVATIONS (NUM,HEURE,NBRP) values ('7','89','66');
Insert into SKANDER.RESERVATIONS (NUM,HEURE,NBRP) values ('1','12','7');
Insert into SKANDER.RESERVATIONS (NUM,HEURE,NBRP) values ('10','14','20');
--------------------------------------------------------
--  DDL for Index TABLE2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKANDER"."TABLE2_PK" ON "SKANDER"."COMMANDES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKANDER"."TABLE1_PK" ON "SKANDER"."RESERVATIONS" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "SKANDER"."COMMANDES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SKANDER"."COMMANDES" ADD CONSTRAINT "TABLE2_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "SKANDER"."RESERVATIONS" MODIFY ("NUM" NOT NULL ENABLE);
 
  ALTER TABLE "SKANDER"."RESERVATIONS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
